# See https://www.freedesktop.org/software/systemd/man/latest/systemd-gpt-auto-generator.html
[Partition]
Type=c12a7328-f81f-11d2-ba4b-00a0c93ec93b
Label=ESP
Format=vfat
# Careful with the min size: https://github.com/systemd/systemd/issues/37801
SizeMinBytes=${BOOTSIZE}
SizeMaxBytes=${BOOTSIZE}
